# Generated by Django 3.2.7 on 2021-10-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeduser',
            name='prefered_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
